### ISSUE TITLE
Theme with json files not coloring correctly after sublime text update

### ISSUE THREAD

**Issue by jzatarain** [enkia/enki-theme#17]
In build 3200 of sublime text, the colors for json files is now showing everything in just blue and white.
`"color_scheme": "Packages/Enki Theme/scheme/Enki.tmTheme",
	"enki_theme_accent_samon": true,
	"enki_theme_compact_panel": true,
	"enki_theme_compact_sidebar": true,
	"enki_theme_panel_separator": true,
	"enki_theme_small_statusbar": true,
	"enki_theme_small_tab": true,
	"enki_theme_tabs_autowidth": true,
	"enki_theme_tabs_separator": true,
	"enki_theme_tree_headings": true,
	"font_options":
	[
		"gray_antialias",
		"subpixel_antialias"
	],
	"font_size": 13,`

**Comment by enkia** [comment]
Apologies for the long delay but this issue is fixed in the latest release. Package Control isn't updated yet but should be soon!

**Comment by jzatarain** [comment]
I believe I got the package update, but I'm still seeing json files in blue and white.
Using sublime text build 3207

**Comment by enkia** [comment]
Babel and JavaScriptNext packages haven't updated their syntax for json in awhile so I went with Sublime's more recently updated default package for json. How does it look with Javascript > JSON?

**Comment by jzatarain** [comment]
It looks like this with or without the theme.
![image](https://user-images.githubusercontent.com/20093580/57864922-51b9c280-77c2-11e9-9b80-2fadecafe24d.png)

**Comment by jzatarain** [comment]
So it won't be fixed?

**Comment by enkia** [comment]
@jzatarain can you tell me what JSON syntax definition you're using? It's located in the lower right hand corner:

![image](https://user-images.githubusercontent.com/255730/68075642-d902ee80-fd80-11e9-9aab-841b1e8c6e54.png)

Clicking on it brings up a list. For example, you can switch to Sublime's new implementation by going to Javascript > JSON.

![image](https://user-images.githubusercontent.com/255730/68075659-16677c00-fd81-11e9-86cd-a4f54323731c.png)

Or open all .json types as that type at the top.

**Comment by jzatarain** [comment]
It currently looks like this, closing 
![image](https://user-images.githubusercontent.com/20093580/158554854-24129f66-17ff-4a76-b571-2f70747e6fab.png)
